[mypy]
python_version = 3.11
files = app, tests, worker.py
mypy_path = .
pretty = True
show_error_codes = True
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
check_untyped_defs = True
ignore_missing_imports = True
explicit_package_bases = True
exclude = (^\.venv/|^data/)

[mypy-tests.*]
disable_error_code = var-annotated
