apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: neuralflow

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - redis.yaml
  - chromadb.yaml
  - postgres.yaml
  - api.yaml
  - worker.yaml
  - frontend.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
